*** Main models to Latex	
capture lab var split "Divided group"
capture lab var tfrac "Fractionalization"
capture lab var tfrac_incr_post1946 "Frac. incr. since 1946"
capture lab var tfrac_incr_post1918 "Frac. incr. since 1918"
capture lab var tfrac_incr_pre1946 "Frac. incr. before 1946"
capture lab var tfrac_incr "Frac. incr. since 1886"
capture lab var tfrac_hist_incr "Frac. incr. since 1886 (1918 map)"
capture lab var ln_ag_area_sqkm "Territory km$^2$, log"
capture lab var ag_incidence_flag_lag "Ongoing conflict, lag"
capture lab var ag_allexcl "All excl. in AG"
capture lab var ag_incl "Incl. in AG"
capture lab var status_excl "Exclusion"
capture lab var downgraded2 "Downgraded"
capture lab var rbal "Relative size"
capture lab var warhist "War history"
capture lab var ln_rgdppc_lag "GDP, lag, log"
capture lab var ln_pop_lag "Population, log"
capture lab var ln_capdist "Distance to capital, log"
capture lab var colonial_past "Colonial history"
capture lab var ln_state_age "State age, log"
capture lab var pys "Peace years"
capture lab var pys2 "Peace years$^2$"
capture lab var pys3 "Peace years$^3$"
capture lab var ag_warhist "War history"
capture lab var ag_incidence_flag_lag "Conflict, lag"
capture lab var ag_excl_share "Excluded AG share"
capture lab var pfrac "Pop. fractionalization"
capture lab var pfrac_incr_post1946 "Pop. frac. incr. since 1946"
capture lab var pfrac_incr "Pop. frac. incr. since 1886"
capture lab var tfrac_1918_incr_comp "Frac. incr. since 1886 (1918 map)"
capture lab var tfrac_comp_incr "Frac. incr. since 1886 (1918 map)"
